# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
